security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/me
server:
  port: 8088
  servlet:
    context-path: /client
spring:
  main:
    allow-bean-definition-overriding: true